# Generated by Django 5.0.4 on 2024-04-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Matrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matrix_text",
                    models.TextField(verbose_name="Text Representation of Matrix"),
                ),
            ],
        ),
    ]
